### Get all users
GET http://localhost:8080/user
Content-Type: application/json

### Get user by id
GET http://localhost:8080/user/67954da63a0496131f3192e4
Content-Type: application/json

### Create user
POST http://localhost:8080/user
Content-Type: application/json

{
    "firstname": "Jorge",
    "lastname": "Burgoa",
    "username": "jorge@email.com",
    "password": "Sup3r53gur0"
}

### Get all tickets
GET http://localhost:8080/ticket
Content-Type: application/json

### Get ticket by id
GET http://localhost:8080/ticket/67955fff8a21e65f1be2fb54
Content-Type: application/json

### Create ticket
POST http://localhost:8080/ticket
Content-Type: application/json

{
    "title": "Nunc cursus pharetra lectus, at pellentesque enim sagittis sed",
    "description": "Sed sollicitudin egestas ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla facilisi. Donec ullamcorper mi eget rutrum lacinia. Fusce tincidunt lacus quis augue accumsan, eget congue tellus tincidunt.",
    "userOwnerId": "679570b9f89b9fd7b0f7cef4"
}